### PR TITLE
Please remove this repository

### PR DESCRIPTION
**Pull request by Memnarch**
This is just a Dummymerge to message you ;)
Please remove this repository. I have just pushed an update to Delphinus, which SGlienke requested to continue maintain his own Delphinuspackage. Otherwhise this will confuse future users(or cause conflcits when linking Delphinuspackages)
http://memnarch.bplaced.net/blog/2017/07/delphinus-externaltimelines-bitbucket-mobile-linux/

### CODE REVIEW

**Comment by Memnarch** [comment]
@Pawe1 ping! :P

**Comment by Memnarch** [comment]
"not without a reason"
and
"for a reason"
are both correct ;)

**Comment by Pawe1** [comment]
@Memnarch Sorry for delay - my notification channels are not working 24/24
I have deleted Delphinus.*.json files so package is now not visible.
I hope Stefan will make updates soon 😄

**Comment by Memnarch** [comment]
Yes now it is invisible, but still found :P
You can keep the files but need to remove the Delphinus-Support text form the readme ;)

**Comment by Pawe1** [comment]
oh...
:white_check_mark: Done

**Comment by Pawe1** [comment]
@Memnarch I see that Stefan updated Spring4D repository 😁 Nice!
There are now 2 packages supporting Linux / Android already :]

I have found another interesting "victim" to test new features: https://bitbucket.org/gmurt/kscomponents 😉 

[I'm deleting this repository because it became pointless]

**Pull request closed without merging**
